const WORKER_BASE_URL = "https://yamada-api.kansuu805030.workers.dev";
const stations=[
{id:"dam",name:"竜神ダム",type:"ダム情報",status:"green",statusText:"観測中",dam:true,dataUrl:"https://kasen-pref-ibaraki.jp/Sta/GetDamStaData?obsTime=&obsStaId=476",levels:{min:136,floodSeason:146.5,normalFull:152.5,emergency:156.8,floodFull:159},flow:{maxRelease:20,flood:14.5}},
{id:"shimotakakura",name:"下高倉",type:"河川カメラ",status:"green",statusText:"カメラ",camera:{recent:{kind:"ibaraki",id:"534",offset:10},old:{kind:"ibaraki",id:"534",offset:40},normal:"https://kasen-pref-ibaraki.jp/Layers/Camera/NomalTime/534.jpg"}},
{id:"amanoya",name:"天下野",type:"水位観測点",status:"green",statusText:"観測中",dataType:"A",dataUrl:"https://kasen-pref-ibaraki.jp/Sta/GetWaterLevelStaData?obsTime=&obsStaId=334",levels:{B:1.4,C:1.9,D:2.2}},
{id:"kuniyasu",name:"国安",type:"危機管理型水位計",status:"yellow",statusText:"観測中",dataType:"B",dataUrl:"https://kasen-pref-ibaraki.jp/Sta/GetKikikanriStaData?obsTime=&obsStaId=454",levels:{X:-3.56,E:0}},
{id:"wada",name:"和田",type:"水位観測点・河川カメラ",status:"orange",statusText:"観測中",dataType:"A",dataUrl:"https://kasen-pref-ibaraki.jp/Sta/GetWaterLevelStaData?obsTime=&obsStaId=335",levels:{B:2.6,C:3.1,D:3.6},camera:{recent:{kind:"ibaraki",id:"535",offset:10},old:{kind:"ibaraki",id:"535",offset:40},normal:"https://kasen-pref-ibaraki.jp/Layers/Camera/NomalTime/535.jpg"}},
{id:"tokoi",name:"常井橋",type:"水位観測点・河川カメラ",status:"red",statusText:"観測中",dataType:"A",dataUrl:"https://kasen-pref-ibaraki.jp/Sta/GetWaterLevelStaData?obsTime=&obsStaId=333",levels:{A:2,B:3,C:3.5,D:3.8,E:4.3},camera:{recent:{kind:"river",id:"cctv_080004_31C03035",offset:20},old:{kind:"river",id:"cctv_080004_31C03035",offset:50},normal:"https://cam.river.go.jp/cam/normal/cctv_080004_31C03035.jpg"}}
];
const levelInfo={A:["水防団待機水位","#16834b"],B:["氾濫注意水位","#d5a400"],C:["避難判断水位","#d64b2a"],D:["氾濫危険水位","#8b3fb0"],E:["氾濫発生水位","#222"],X:["観測開始水位","#65c7df"]};
const charts={},cache=new Map();
const proxy=u=>WORKER_BASE_URL.replace(/\/$/,"")+"/api?url="+encodeURIComponent(u);
async function fetchJson(u){if(cache.has(u))return cache.get(u);const r=await fetch(proxy(u),{cache:"no-store"});if(!r.ok)throw Error(`HTTP ${r.status}`);const j=await r.json();cache.set(u,j);return j}
function pt(s){const m=String(s).match(/^(\d{4})\/(\d{2})\/(\d{2})\s+(\d{2}):(\d{2})/);return m?new Date(+m[1],+m[2]-1,+m[3],+m[4],+m[5]):null}
function series(item,conv=x=>x){return(item?.dataList||[]).map(r=>{const t=pt(r.time),v=conv(Number(r.data));return t&&Number.isFinite(v)?{time:t,value:v}:null}).filter(Boolean).sort((a,b)=>a.time-b.time)}
function item(j,id){return(j?.tableData?.itemDataList||[]).find(x=>String(x.dataItemId)===String(id))}
function last12(a,end){if(!a.length)return[];const e=(end||a.at(-1).time).getTime();return a.filter(x=>x.time.getTime()>=e-43200000&&x.time.getTime()<=e)}
function oneHour(a,cur){if(!a.length||!cur)return null;const target=cur.time.getTime()-3600000;return a.reduce((b,x)=>Math.abs(x.time-target)<Math.abs(b.time-target)?x:b,a[0])}
function diff1h(a,cur){const p=oneHour(a,cur);return p&&Math.abs(cur.time-p.time)<=900000?cur.value-p.value:null}
function fmt(v,d=2){return v==null?"--":Number(v).toFixed(d)}
function arrow(v){return v>0?"↑":v<0?"↓":"→"} function cls(v){return v>0?"up":v<0?"down":"flat"}
async function load(s){try{const j=await fetchJson(s.dataUrl);if(s.dam){const l=series(item(j,10)),i=series(item(j,50)),o=series(item(j,70)),e=[l,i,o].filter(a=>a.length).map(a=>a.at(-1).time).sort((a,b)=>a-b).at(-1);return{level:last12(l,e),inflow:last12(i,e),outflow:last12(o,e),rawTime:j?.tableData?.obsTime||""}}const wi=item(j,10);const x=series(wi,s.dataType==="B"?n=>-n/100:n=>n);return{data:last12(x),rawTime:j?.tableData?.obsTime||"",itemFound:!!wi}}catch(e){return{sError:e.message,data:[],level:[],inflow:[],outflow:[],rawTime:"",error:e.message}}}
function camTime(off){const d=new Date(Date.now()-off*60000);d.setSeconds(0,0);d.setMinutes(Math.floor(d.getMinutes()/10)*10);return d}
function stamp(d){return`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}${String(d.getHours()).padStart(2,"0")}${String(d.getMinutes()).padStart(2,"0")}`}
function camUrl(s){const d=camTime(s.offset),st=stamp(d);return s.kind==="river"?`https://cam.river.go.jp/cam/history/${st}/${s.id}.jpg`:`https://kasen-pref-ibaraki.jp/Layers/Camera/${d.getFullYear()}/${String(d.getMonth()+1).padStart(2,"0")}/${String(d.getDate()).padStart(2,"0")}/${st}_${s.id}.jpg`}
function camera(s,label){const u=s.kind==="normal"?s.normal:camUrl(s);return`<div class="camera-card"><img src="${u}" alt="${label}" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><div class="camera-error" style="display:none">画像を取得できませんでした</div><div class="camera-caption">${label}</div></div>`}
function chartBase(y1="水位 (m)"){return{responsive:true,maintainAspectRatio:false,parsing:false,interaction:{mode:"nearest",intersect:false},scales:{x:{type:"linear",ticks:{maxTicksLimit:7,callback:v=>new Date(v).toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}},y:{title:{display:true,text:y1}},y2:{position:"right",title:{display:true,text:"流量 (m³/s)"},grid:{drawOnChartArea:false}}},plugins:{legend:{display:true,position:"bottom",labels:{font:{size:10}}}}}}
function makeDamChart(s,r){const c=document.getElementById("chart-"+s.id);if(charts[s.id])charts[s.id].destroy();const all=[...r.level,...r.inflow,...r.outflow];if(!all.length)return;const lo=all[0].time.getTime(),hi=all.at(-1).time.getTime();const line=(label,a,color,yAxis)=>({label,data:a.map(x=>({x:x.time.getTime(),y:x.value})),borderColor:color,borderWidth:2,pointRadius:1,tension:.2,yAxisID:yAxis});const h=(label,v,color,yAxis)=>({label,data:[{x:lo,y:v},{x:hi,y:v}],borderColor:color,borderWidth:2,borderDash:[6,4],pointRadius:0,yAxisID:yAxis});charts[s.id]=new Chart(c,{type:"line",data:{datasets:[line("貯水位",r.level,"#1769aa","y"),line("流入量",r.inflow,"#2c8a52","y2"),line("放流量",r.outflow,"#d66a2a","y2"),h("洪水期制限水位 146.50m",146.5,"#d5a400","y"),h("常時満水位 152.50m",152.5,"#16834b","y"),h("異常洪水時防災操作開始水位 156.80m",156.8,"#d64b2a","y"),h("洪水時満水位 159.00m",159,"#8b3fb0","y"),h("計画最大放流量 20.000m³/s",20,"#222","y2"),h("洪水量 14.500m³/s",14.5,"#b14f8a","y2")]},options:chartBase()});setDamMode(s.id,"all")}
function setDamMode(id,mode){const c=charts[id];if(!c)return;c.data.datasets.forEach(d=>{const w=/^(貯水位|洪水期|常時|異常洪水|洪水時)/.test(d.label),f=/^(流入量|放流量|計画最大|洪水量)/.test(d.label);d.hidden=mode==="water"?!w:mode==="flow"?!f:false});c.update();document.querySelectorAll(`[data-chart="${id}"]`).forEach(b=>b.classList.toggle("active",b.dataset.mode===mode))}
function makeWaterChart(s,a){const c=document.getElementById("chart-"+s.id);if(!c)return;if(charts[s.id])charts[s.id].destroy();if(!a.length){console.warn("水位データなし",s.id);return;}const lo=a[0].time.getTime(),hi=a.at(-1).time.getTime(),ds=[{label:"水位",data:a.map(x=>({x:x.time.getTime(),y:x.value})),borderColor:"#1769aa",backgroundColor:"rgba(23,105,170,.08)",fill:true,borderWidth:3,pointRadius:1,tension:.2}];for(const[k,v]of Object.entries(s.levels)){const inf=levelInfo[k];ds.push({label:`${k}: ${inf[0]} (${v.toFixed(2)}m)`,data:[{x:lo,y:v},{x:hi,y:v}],borderColor:inf[1],borderWidth:2,borderDash:[6,4],pointRadius:0})}charts[s.id]=new Chart(c,{type:"line",data:{datasets:ds},options:{...chartBase(),scales:{x:chartBase().scales.x,y:{title:{display:true,text:"水位 (m)"}},y2:{display:false}}}})}
function renderDam(s,i,r){const cur=r.level.at(-1),cd=diff1h(r.level,cur),inf=r.inflow.at(-1),od=r.outflow.at(-1),rate=cur?(cur.value-s.levels.min)/(s.levels.floodFull-s.levels.min)*100:null;const id=s.id;return`<article class="station-card" id="${id}"><div class="station-header"><div><h3>${i+1}. ${s.name}</h3><div class="station-type">${s.type}</div></div><span class="status green">${s.statusText}</span></div><div class="station-body"><div class="water-panel"><div class="water-label">貯水率</div><div class="water-value">${fmt(rate,1)}<span class="unit">%</span></div><div class="change ${cls(cd)}">${cd==null?"1時間変化 --":`${arrow(cd)} ${Math.abs(cd).toFixed(2)} m（1時間前比）`}</div><div class="sub-values"><div class="sub-value"><div class="label">放流量</div><div class="value">${fmt(od?.value,3)} <small>m³/s</small></div><div class="sub-change ${cls(diff1h(r.outflow,od))}">${diff1h(r.outflow,od)==null?"1時間変化 --":`${arrow(diff1h(r.outflow,od))} ${Math.abs(diff1h(r.outflow,od)).toFixed(3)} m³/s`}</div></div><div class="sub-value"><div class="label">流入量</div><div class="value">${fmt(inf?.value,3)} <small>m³/s</small></div><div class="sub-change ${cls(diff1h(r.inflow,inf))}">${diff1h(r.inflow,inf)==null?"1時間変化 --":`${arrow(diff1h(r.inflow,inf))} ${Math.abs(diff1h(r.inflow,inf)).toFixed(3)} m³/s`}</div></div></div><div class="water-label">貯水位：${fmt(cur?.value)}m</div><div class="water-label">${r.rawTime||""}</div></div><div class="chart-wrap"><div class="chart-title">直近12時間のダム情報</div><div class="chart-controls"><button class="chart-btn active" data-chart="${id}" data-mode="all" onclick="setDamMode('${id}','all')">すべて</button><button class="chart-btn" data-chart="${id}" data-mode="water" onclick="setDamMode('${id}','water')">貯水位・基準水位</button><button class="chart-btn" data-chart="${id}" data-mode="flow" onclick="setDamMode('${id}','flow')">流入量・放流量・流量基準量</button></div><canvas id="chart-${id}"></canvas></div></div><details class="explanation" open><summary>■ 基準量の説明</summary><dl><dt>○貯水位基準水位</dt><dd>最低水位：136.00m</dd><dd>洪水期制限水位：6月21日～10月10日の貯められる上限（146.50m）</dd><dd>常時満水位：10月11日～6月20日の貯められる上限（152.50m）</dd><dd>異常洪水時防災操作開始水位：いわゆる緊急放流準備開始水位（156.80m）</dd><dd>洪水時満水位：計画上の最高水位（これ以上貯められない）（159.00m）</dd><dd>貯水率：洪水時満水位に対する現在の貯水位の割合。計算式は（貯水位－最低水位）÷（洪水時満水位－最低水位）×100。</dd><dt>○流量基準量</dt><dd>計画最大放流量：洪水調節時にダムから放流できる最大量（20.000m³/s）</dd><dd>洪水量：洪水調節を開始する目安となる流入量（14.500m³/s）</dd></dl></details></article>`}
function renderWater(s,i,r){const cur=r.data.at(-1),d=diff1h(r.data,cur);return`<article class="station-card" id="${s.id}"><div class="station-header"><div><h3>${i+1}. ${s.name}</h3><div class="station-type">${s.type}</div></div><span class="status ${s.status}">${s.statusText}</span></div><div class="station-body"><div class="water-panel"><div class="water-label">${s.dataType==="B"?"氾濫発生までの距離":"現在水位"}</div><div class="water-value">${fmt(cur?.value)}<span class="unit">m</span></div><div class="change ${cls(d)}">${d==null?"1時間変化 --":`${arrow(d)} ${Math.abs(d).toFixed(2)} m（1時間前比）`}</div><div class="water-label">基準水位：グラフ内に表示</div></div><div class="chart-wrap"><div class="chart-title">直近12時間の水位</div><canvas id="chart-${s.id}"></canvas></div></div></article>`}
function renderCamera(s,i){return`<article class="station-card" id="${s.id}"><div class="station-header"><div><h3>${i+1}. ${s.name}</h3><div class="station-type">${s.type}</div></div><span class="status ${s.status}">${s.statusText}</span></div><div class="camera-section"><h4>📷 河川カメラ</h4><div class="camera-grid">${camera(s.camera.recent,"直近")}${camera(s.camera.old,"約30分前")}${camera({kind:"normal",normal:s.camera.normal},"平常時")}</div></div></article>`}
function renderSummary(){document.getElementById("stationSummary").innerHTML=stations.map((s,i)=>`<button class="summary-item" onclick="document.getElementById('${s.id}').scrollIntoView({behavior:'smooth',block:'center'})"><span class="summary-number">${i+1}</span><span class="summary-name">${s.name}</span><span class="summary-status">${s.statusText}</span></button>`).join("")}
async function render(){renderSummary();const list=document.getElementById("stationList");list.innerHTML=stations.map((s,i)=>`<article class="station-card" id="${s.id}"></article>`).join("");for(let i=0;i<stations.length;i++){const s=stations[i];if(!s.dataUrl){document.getElementById(s.id).outerHTML=renderCamera(s,i);continue}const r=await load(s);document.getElementById(s.id).outerHTML=s.dam?renderDam(s,i,r):renderWater(s,i,r);try{if(s.dam)makeDamChart(s,r);else makeWaterChart(s,r.data)}catch(e){console.error("グラフ生成エラー",s.id,e);const card=document.getElementById(s.id);if(card){const w=card.querySelector(".chart-wrap");if(w)w.insertAdjacentHTML("beforeend",`<div class="chart-error">グラフ生成エラー：${e.message}</div>`)}}}document.getElementById("message").textContent="公式データを取得しました。増減は1時間前との比較です。"}
document.getElementById("refreshBtn").addEventListener("click",()=>{cache.clear();render();updateTime()});function updateTime(){document.getElementById("updatedAt").textContent="ページ更新："+new Date().toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}render();updateTime();
